### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by okram999** [atorman/elfPy#3]
Was working till last week. 

```
check point
Traceback (most recent call last):
  File ".\elf.py", line 239, in <module>
    download_elf()
  File ".\elf.py", line 115, in download_elf
    access_token, instance_url = login()
  File ".\elf.py", line 97, in login
    res = urllib2.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 397, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by okram999** [comment]
# Fixed .. 
Implemented the SSL Context as TLS1.0 was disabled on the server
